### ISSUE TITLE
iPhone 5

### ISSUE THREAD

**Issue by jnoy** [TaeHagen/relayserver#1]
Hi, I have an iPhone 5, on iOS 10.3.4 and this won't run. Are there any plans to update for this? Thanks!

**Comment by SpaceSaver** [comment]
Hi @jnoy can you provide any more info about what went wrong?

**Comment by jnoy** [comment]
Yeah, the .deb won't run on an iPhone 5, which is armv7s. It looks like only arm64 is supported, and I have attempted to compile for armv7s but failed. I do not know if it is possible to compile for that architecture or if I just don't know what I am doing, but I have given up on it at this point.

**Comment by TaeHagen** [comment]
IOS/arm32 is not supported by rust anymore.
